/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GetQuoteRouteImport } from './routes/get-quote'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiPublicQuoteSubmissionsRouteImport } from './routes/api/public/quote-submissions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GetQuoteRoute = GetQuoteRouteImport.update({
  id: '/get-quote',
  path: '/get-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuoteSubmissionsRoute =
  ApiPublicQuoteSubmissionsRouteImport.update({
    id: '/api/public/quote-submissions',
    path: '/api/public/quote-submissions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/get-quote': typeof GetQuoteRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/public/quote-submissions': typeof ApiPublicQuoteSubmissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get-quote': typeof GetQuoteRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/public/quote-submissions': typeof ApiPublicQuoteSubmissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/get-quote': typeof GetQuoteRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/public/quote-submissions': typeof ApiPublicQuoteSubmissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/get-quote' | '/admin/login' | '/api/public/quote-submissions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/get-quote' | '/admin/login' | '/api/public/quote-submissions'
  id:
    | '__root__'
    | '/'
    | '/get-quote'
    | '/admin/login'
    | '/api/public/quote-submissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GetQuoteRoute: typeof GetQuoteRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiPublicQuoteSubmissionsRoute: typeof ApiPublicQuoteSubmissionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-quote': {
      id: '/get-quote'
      path: '/get-quote'
      fullPath: '/get-quote'
      preLoaderRoute: typeof GetQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/quote-submissions': {
      id: '/api/public/quote-submissions'
      path: '/api/public/quote-submissions'
      fullPath: '/api/public/quote-submissions'
      preLoaderRoute: typeof ApiPublicQuoteSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GetQuoteRoute: GetQuoteRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiPublicQuoteSubmissionsRoute: ApiPublicQuoteSubmissionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
